#!/usr/bin/env python
import re
import os
import sys
import shutil
import urllib
import argparse
import tempfile
import itertools
import subprocess
import ConfigParser
import multiprocessing
import requests
import lxml.html

HEADERS = {
    'Connection': 'keep-alive',
    'Cache-Control': 'max-age=0',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3)'\
        'AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.79'\
        'Safari/535.11',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9'\
        ',*/*;q=0.8',
    'Accept-Encoding': 'gzip,deflate,sdch',
    'Accept-Language': 'en-US,en;q=0.8',
    'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3'
}

class Tracker(object):
    def __init__(self, username, password):
        self.session = requests.Session()
        self.session.headers.update(HEADERS)
        self.login(username, password)

class Bibliotik(Tracker):

    FORMATS = {
        '.pdf': '2',
        '.mobi': '16',
        '.epub': '15',
    }

    def login(self, username, password):
        params = {'username': username, 'password': password}
        self.session.post('http://bibliotik.org/login', params)

        r = self.session.get('http://bibliotik.org/upload/ebooks')
        doc = lxml.html.fromstring(r.text)
        self.authkey = doc.xpath('//*[@id="body"]/form/input[2]')[0].attrib['value']
        self.announce = doc.xpath('//*[@id="body"]/p/input')[0].attrib['value']
        self.name = "Bibliotik"

    def upload(self, filename, torrent, metadata):
        files = {'TorrentFileField': open(torrent, 'rb')}
        data = {
            'upload': '',
            'authkey': self.authkey,
            'AuthorsField': metadata['authors'],
            'TitleField': metadata['title'],
            'IsbnField': metadata['isbn'],
            'PublishersField': metadata['publisher'],
            'PagesField': metadata['pages'],
            'YearField': metadata['year'],
            'FormatField': self.FORMATS[os.path.splitext(filename)[-1]],
            'LanguageField': '1',
            'TagsField': 'nonfiction', # FIXME
            'ImageField': metadata['image'],
            'DescriptionField': metadata['description'],
        }
        for key, value in data.items():
            data[key] = value.encode('utf-8')

        r = self.session.post('http://bibliotik.org/upload/ebooks', files=files, data=data)
        return True

    def fetch_metadata(self, isbn):
        params = {'isbn': isbn, 'authkey': self.authkey}
        r = self.session.get('http://bibliotik.org/isbnlookup', params=params)
        data = r.json()
        if 'isbn' in data:
            return data
        return None

    def has_book(self, metadata):
        params = {'search': '@isbn %s' % metadata['isbn']}
        r = self.session.get('http://bibliotik.org/torrents/', params=params)
        return 'No torrents found.' not in r.text

class WhatCD(Tracker):
    def login(self, username, password):
        params = {'username': username, 'password': password}
        self.session.post('https://what.cd/login.php', params)

        r = self.session.get('https://what.cd/upload.php')
        doc = lxml.html.fromstring(r.text)
        self.authkey = doc.xpath('//*[@id="upload_table"]/div[1]/input[2]')[0].attrib['value']
        self.announce = doc.xpath('//*[@id="content"]/div[2]/p/input')[0].attrib['value']
        self.name = "What.CD"

    def upload(self, filename, torrent, metadata):
        files = {'file_input': open(torrent, 'rb')}
        data = {
            'submit': 'true',
            'auth': self.authkey,
            'type': '2',
            'title': "%s - %s" % (metadata['authors'], metadata['title']),
            'tags': 'non.fiction',
            'image': metadata['image'],
            'desc': metadata['description'],
        }
        for key, value in data.items():
            data[key] = value.encode('utf-8')

        r = self.session.post('https://what.cd/upload.php', files=files, data=data)
        return True

    def has_book(self, metadata):
        params = {'searchstr': metadata['title'], 'filter_cat[3]': 1}
        r = self.session.get('https://what.cd/torrents.php', params=params)
        return 'Your search did not match anything.' not in r.text

class STP(Tracker):

    FORMATS = {
        '.pdf': 'PDF',
        '.epub': 'EPUB',
        '.mobi': 'MOBI',
    }

    def login(self, username, password):
        params = {'username': username, 'password': password}
        self.session.post('https://stopthepress.es/login.php', params)

        r = self.session.get('https://stopthepress.es/upload.php')
        doc = lxml.html.fromstring(r.text)
        self.authkey = doc.xpath('//*[@id="upload_table"]/div[1]/input[2]')[0].attrib['value']
        self.announce = doc.xpath('//*[@id="content"]/div[2]/p/input')[0].attrib['value']
        self.name = "STP"

    def upload(self, filename, torrent, metadata):
        authors = [author.strip().encode('utf-8') for author in metadata['authors'].split(',')]
        files = {'file_input': open(torrent, 'rb')}
        data = {
            'submit': 'true',
            'auth': self.authkey,
            'type': '4',
            'authors[]': authors,
            'importance[]': ['1' for author in authors],
            'title': metadata['title'].encode('utf-8'),
            'record_label': metadata['publisher'].encode('utf-8'),
            'catalogue_number': metadata['isbn'],
            'year': metadata['year'],
            'format': self.FORMATS[os.path.splitext(filename)[-1]],
            'media': 'Unknown',
            'tags': 'non.fiction',
            'image': metadata['image'],
            'album_desc': metadata['description'].encode('utf-8'),
            'release_desc': 'Created with [url=https://github.com/zacharydenton/alexandria]alexandria[/url].',
        }

        if data['year'] == '2012':
            data['tags'] += ', contest.2012'

        r = self.session.post('https://stopthepress.es/upload.php', data=data, files=files)
        return True

    def has_book(self, metadata):
        params = {'cataloguenumber': metadata['isbn']}
        r = self.session.get('https://stopthepress.es/torrents.php', params=params)
        return 'Your search did not match anything.' not in r.text

def locate(root, match_function):
    for path, dirs, files in os.walk(root):
        for filename in (os.path.abspath(os.path.join(path, filename)) for filename in files if match_function(filename)):
            yield filename

def is_book(filename):
    extension = os.path.splitext(filename)[-1].lower()
    return extension in ['.pdf', '.epub', '.mobi']

def make_torrent(filename, announce, piece_size=16):
    torrent = subprocess.check_output(['mktemp', '-u', '--suffix', '.torrent']).strip()
    command = ['mktorrent', '-p', '-a', announce, '-l', str(piece_size), '-o', torrent, filename]
    subprocess.check_output(command, stderr=subprocess.STDOUT)
    return torrent

def fetch_metadata(isbn):
    params = {'bibkeys': 'ISBN:%s' % isbn, 'jscmd': 'details', 'format': 'json'}
    r = requests.get('http://openlibrary.org/api/books', params=params)
    data = r.json()
    if data:
        return data
    else:
        return None

def parse_config(config_path):
    config = ConfigParser.SafeConfigParser()

    if os.path.isfile(config_path):
        config.read(config_path)
    else:
        config_dir = os.path.dirname(config_path)
        if not os.path.isdir(config_dir):
            os.makedirs(config_dir)

        config.add_section('global')
        config.set('global', 'torrent_dir', '')
        config.set('global', 'data_dir', '')

        config.add_section('bibliotik')
        config.set('bibliotik', 'username', '')
        config.set('bibliotik', 'password', '')

        config.add_section('whatcd')
        config.set('whatcd', 'username', '')
        config.set('whatcd', 'password', '')

        config.add_section('stp')
        config.set('stp', 'username', '')
        config.set('stp', 'password', '')

        with open(config_path, 'w') as f:
            config.write(f)

        print 'Please edit the configuration file: %s' % config_path
        sys.exit(2)

    return config

def extract_isbn(filename):
    match = re.search('(\d{10}|\d{13})', filename)
    if match:
        return match.group()

    command = ['pdftotext', '-f', '1', '-l', '10', filename, '-']
    text = subprocess.check_output(command)
    match = re.search('(?:[0-9]{3}-)?[0-9]{1,5}-[0-9]{1,7}-[0-9]{1,6}-[0-9]', text)
    if match:
        return match.group().replace('-', '')

    return None

def rename_ebook(original, output_dir, metadata):
    new_filename = os.path.join(output_dir, "%s (%s)%s" % (metadata['title'], metadata['isbn'], os.path.splitext(original)[-1]))
    shutil.copy(original, new_filename)
    return new_filename

def upload(filename, config, trackers):
    print
    isbn = extract_isbn(filename)
    if not isbn:
        print "Failed to extract ISBN from:", filename
        return None

    metadata = fetch_metadata(isbn)
    if not metadata:
        return None

    print "Book found: %s (%s) [%s]" % (metadata['title'], metadata['year'], os.path.splitext(filename)[1][1:].upper())
    ebook = rename_ebook(filename, os.path.expanduser(config.get('global', 'data_dir')), metadata)

    for i, tracker in enumerate(trackers):
        try:
            if tracker.has_book(metadata):
                continue

            print "Uploading to %s..." % tracker.name,

            # create each tracker's torrent with a different piece size so
            # that the torrents each have different info hashes (otherwise only one will seed in rtorrent)
            torrent = make_torrent(ebook, tracker.announce, piece_size=15+i)

            if not tracker.upload(ebook, torrent, metadata):
                print "failed!"
                continue
    
            shutil.copy(torrent, os.path.expanduser(config.get('global', 'torrent_dir')))
            print "done!"
        except Exception as e:
            print "failed: %s!" % e
            continue

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('book_dirs', nargs='+', help='paths to directories containing books')
    parser.add_argument('--config', help='the location of the configuration file', \
            default=os.path.expanduser('~/.alexandria/config'))

    args = parser.parse_args()
    config = parse_config(args.config)

    trackers = []
    if config.items('bibliotik'):
        username = config.get('bibliotik', 'username')
        password = config.get('bibliotik', 'password')
        if username and password:
            print "Logging into Bibliotik."
            bibliotik = Bibliotik(username, password)
            trackers.append(bibliotik)
            global fetch_metadata
            fetch_metadata = bibliotik.fetch_metadata

    if config.items('whatcd'):
        username = config.get('whatcd', 'username')
        password = config.get('whatcd', 'password')
        if username and password:
            print "Logging into What.CD."
            trackers.append(WhatCD(username, password))

    if config.items('stp'):
        username = config.get('stp', 'username')
        password = config.get('stp', 'password')
        if username and password:
            print "Logging into STP."
            trackers.append(STP(username, password))

    books = itertools.chain(*(locate(book_dir, is_book) for book_dir in args.book_dirs))
    for filename in books:
        upload(filename, config, trackers)

if __name__ == '__main__': main()
